# Generated by Django 3.0.6 on 2021-07-15 20:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=5, max_digits=20, validators=[django.core.validators.MinValueValidator(0, 'Prices must be positive')])),
            ],
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['currency_code'], name='exchangerat_currenc_ca9e11_idx'),
        ),
    ]
