# Generated by Django 2.1.3 on 2018-11-10 10:32

import common.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', common.models.NameField(max_length=150, unique=True)),
                ('base_price', common.models.CentsPriceField(validators=[django.core.validators.MinValueValidator(1, 'Prices must be positive'), django.core.validators.MinValueValidator(1, 'Prices must be positive'), django.core.validators.MinValueValidator(1, 'Prices must be positive')])),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyPriceChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('new_price', common.models.CentsPriceField(validators=[django.core.validators.MinValueValidator(1, 'Prices must be positive'), django.core.validators.MinValueValidator(1, 'Prices must be positive'), django.core.validators.MinValueValidator(1, 'Prices must be positive')])),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.Currency')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='currencypricechange',
            unique_together={('date', 'currency')},
        ),
    ]
