# Generated by Django 2.1.3 on 2018-12-01 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currencypricechange',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='currencypricechange',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='base_price',
        ),
        migrations.DeleteModel(
            name='CurrencyPriceChange',
        ),
    ]
