# Generated by Django 2.1.5 on 2019-06-09 22:22

import currencies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_auto_20181201_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='code',
            field=models.CharField(db_index=True, max_length=3, null=True, unique=True, validators=[currencies.models.validate_currency_code]),
        ),
    ]
