# Generated by Django 2.2.2 on 2019-08-18 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0002_transaction_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Account'),
        ),
    ]
