# Generated by Django 3.0.6 on 2021-12-15 01:07

import common.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0004_movement_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True, validators=[common.models.tag_validator])),
                ('value', models.CharField(blank=True, max_length=120, null=True, validators=[common.models.tag_validator])),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='movements.Transaction')),
            ],
        ),
    ]
