# Generated by Django 3.0.6 on 2021-05-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('valid_until', models.DateTimeField()),
            ],
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['value'], name='pacs_auth_t_value_e8f6dd_idx'),
        ),
    ]
