# Generated by Django 3.0.6 on 2021-12-02 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacs_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ApiKeyRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.TextField()),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacs_auth.ApiKey')),
            ],
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['value'], name='pacs_auth_a_value_193f8b_idx'),
        ),
        migrations.AddIndex(
            model_name='apikeyrole',
            index=models.Index(fields=['api_key'], name='pacs_auth_a_api_key_16038d_idx'),
        ),
    ]
