# Generated by Django 3.0.6 on 2021-12-03 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacs_auth', '0002_auto_20211202_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeyrole',
            name='api_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='pacs_auth.ApiKey'),
        ),
    ]
